import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavComponent } from "@/components/navbar";
import { Banner } from "@/components/banner";
import { Devloper } from "@/components/Devloper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Banner />
        <NavComponent />
        <main className={inter.className}>{children}</main>
        <Devloper />
      </body>
    </html>
  );
}
